volumes:
  postgres-volume:
    external: false

  postiz-redis-data:
    external: false

  postiz-config:
    external: false

networks:
  proxy:
    external: true
  postiz-network:
    external: false

services:
  postiz:
    image: ghcr.io/gitroomhq/postiz-app:latest
    container_name: postiz
    restart: always
    environment:
      # You must change these. Replace `postiz.adob.dev` with your DNS name - what your web browser sees.
      MAIN_URL: "https://postiz.adob.dev"
      FRONTEND_URL: "https://postiz.adob.dev"
      NEXT_PUBLIC_BACKEND_URL: "https://postiz.adob.dev/api"
      JWT_SECRET: ${JWT_SECRET}

      # These are totally fake values, you must change them with your own Cloudflare R2 settings.
      # Docs: https://docs.postiz.com/configuration/r2
      CLOUDFLARE_ACCOUNT_ID: ${CLOUDFLARE_ACCOUNT_ID}
      CLOUDFLARE_ACCESS_KEY: ${CLOUDFLARE_ACCESS_KEY}
      CLOUDFLARE_SECRET_ACCESS_KEY: ${CLOUDFLARE_SECRET_ACCESS_KEY}
      CLOUDFLARE_BUCKETNAME: ${CLOUDFLARE_BUCKETNAME}
      CLOUDFLARE_BUCKET_URL: ${CLOUDFLARE_BUCKET_URL}
      CLOUDFLARE_REGION: "auto"

      # These defaults are probably fine, but if you change your user/password, update it in the
      # postiz-postgres or postiz-redis services below.
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postiz-postgres:5432/${POSTGRES_DB}"
      REDIS_URL: "redis://postiz-redis:6379"
      BACKEND_INTERNAL_URL: "http://localhost:3000/"
      IS_GENERAL: "true" # Required for self-hosting.
      # Oatuh
      POSTIZ_GENERIC_OAUTH: true
      NEXT_PUBLIC_POSTIZ_OAUTH_DISPLAY_NAME: PocketID
      POSTIZ_OAUTH_URL: https://pid.adob.dev
      POSTIZ_OAUTH_AUTH_URL: https://pid.adob.dev/authorize
      POSTIZ_OAUTH_TOKEN_URL: https://pid.adob.dev/api/oidc/token
      POSTIZ_OAUTH_USERINFO_URL: https://pid.adob.dev/api/oidc/userinfo
      POSTIZ_OAUTH_CLIENT_ID: ${POCKETID_CLIENT_ID}
      POSTIZ_OAUTH_CLIENT_SECRET: ${POCKETID_CLIENT_SECRET}
    volumes:
      - postiz-config:/config/
    ports:
      - 5000:5000
    networks:
      - postiz-network
      - proxy
    depends_on:
      postiz-postgres:
        condition: service_healthy
      postiz-redis:
        condition: service_healthy
    labels:
      homepage.group: Social Media
      homepage.name: Postiz
      homepage.description: A social media platform built with Next.js and TypeScript.
      homepage.icon: postiz.png
      homepage.href: https://postiz.adob.dev
      traefik.enable: true
      traefik.docker.network: proxy
      traefik.http.routers.postiz.entrypoints: web-external
      traefik.http.routers.postiz.rule: Host(`postiz.adob.dev`)
      traefik.http.middlewares.postiz-https-redirect.redirectscheme.scheme: https
      traefik.http.routers.postiz.middlewares: postiz-https-redirect
      traefik.http.routers.postiz-secure.entrypoints: web-secure-external
      traefik.http.routers.postiz-secure.rule: Host(`postiz.adob.dev`)
      traefik.http.routers.postiz-secure.tls: true
      traefik.http.routers.postiz-secure.tls.certresolver: cloudflare
      traefik.http.routers.postiz-secure.middlewares: tinyauth
      traefik.http.services.postiz.loadbalancer.server.port: 5000

  postiz-postgres:
    image: postgres:14.5
    container_name: postiz-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - postiz-network
    healthcheck:
      test: pg_isready -U postiz-user -d postiz-db-local
      interval: 10s
      timeout: 3s
      retries: 3
  postiz-redis:
    image: redis:7.2
    container_name: postiz-redis
    restart: always
    ports:
      - 6379:6379
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - postiz-redis-data:/data
    networks:
      - postiz-network
