networks:
  arrflix:
    external: true
  proxy:
    external: true
  monitoring:
    external: true
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 6969:3000
    networks:
      - arrflix
      - proxy
      - monitoring
    volumes:
      - /home/deds/homepage/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/deds/homepage/logs:/app/logs
      - /mnt/arr:/mnt/arr
    environment:
      # PUID: ${PUID:-1000}
      # PGID: ${PGID:-1000}
      TZ: ${TZ:-UTC}
      HOMEPAGE_ALLOWED_HOSTS: "*"
      LOG_TARGETS: /app/logs/homepage.log
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.homepage-tailscale.entrypoints=tailscale
      - traefik.http.routers.homepage-tailscale.rule=Host(`${TAILNET}`)
      - traefik.http.routers.homepage-tailscale.tls.certresolver=vpnresolver
  internet-speed:
    image: germannewsmaker/myspeed
    container_name: myspeed
    ports:
      - 5216:5216
    networks:
      - arrflix
    volumes:
      - /home/deds/myspeed/logs:/myspeed/data
    environment:
      TZ: ${TZ:-UTC}
    restart: unless-stopped
    labels:
      - homepage.group=Deployment
      - homepage.name=Internet Speed
      - homepage.icon=myspeed.png
      - homepage.href=http://home-ubuntu:5216
      - homepage.widget.type=myspeed
      - homepage.widget.url=http://myspeed:5216
