networks:
  dokploy-network:
    external: true

services:
  cloudflared:
    container_name: cloudflare-tunnel
    image: "cloudflare/cloudflared:latest"
    restart: unless-stopped
    command: "tunnel --no-autoupdate run"
    environment:
      - "TUNNEL_TOKEN=${CF_TUNNEL_TOKEN}" # don't forget to set this in Dokploy Environment
    networks:
      - dokploy-network

    # network_mode: host
    # labels:
    # - homepage.group=Deployment
    # - homepage.title=Cloudflare Tunnel
    # - homepage.icon=cloudflare.png
    # - homepage.widget.type=cloudflared
    # - homepage.widget.accountid=${CLOUDFLARE_ACCOUNT_ID}
    # - homepage.widget.tunnelid=${CLOUDFLARE_TUNNEL_ID}
    # - homepage.widget.key=${CLOUDFLARE_TUNNEL_KEY}

  cloudflare-companion:
    image: tiredofit/traefik-cloudflare-companion
    container_name: cloudflare-companion
    volumes:
      - /home/deds/cloudflare-companion/logs:/logs
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TIMEZONE=America/Sao_Paulo

      - LOG_TYPE=BOTH
      - LOG_LEVEL=INFO

      - TRAEFIK_VERSION=2
      - CF_EMAIL=${CF_EMAIL}
      - CF_TOKEN=${CF_TOKEN}
      - RC_TYPE=CNAME

      - TARGET_DOMAIN=${CF_TARGET_DOMAIN}
      - DOMAIN1=${DOMAIN1}
      - DOMAIN1_ZONE_ID=${DOMAIN1_ZONE_ID}
      #- DOCKER_HOST=tcp://198.51.100.32:2376
      #- DOCKER_CERT_PATH=/docker-certs
      #- DOCKER_TLS_VERIFY=1

      #- TRAEFIK_FILTER_LABEL=traefik.constraint
      #- TRAEFIK_FILTER=proxy-public
    networks:
      - dokploy-network
    restart: always
