networks:
  arrflix:
    driver: bridge
    name: arrflix
  proxy:
    external: true

services:
  # gluetun:
  #   image: qmcgaw/gluetun
  #   cap_add:
  #     - NET_ADMIN
  #   devices:
  #     - /dev/net/tun:/dev/net/tun
  #   environment:
  #     - VPN_SERVICE_PROVIDER=protonvpn
  #     - VPN_TYPE=wireguard
  #     # - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
  #     # - SERVER_COUNTRIES=Netherlands
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=5656
    volumes:
      - ${USERDIR}/docker/qbittorrent:/config
      - ${DATADIR}/Downloads/completed:/data/completed
      - ${DATADIR}/Downloads/incomplete:/data/incomplete
    ports:
      - 5656:5656
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    networks:
      - arrflix
    labels:
      - homepage.group=Arr
      - homepage.name=qBittorrent
      - homepage.icon=qbittorrent.png
      - homepage.href=http://home-ubuntu:5656
      - homepage.description=Torrent client
      - homepage.widget.type=qbittorrent
      - homepage.widget.url=http://qbittorrent:5656
      - homepage.widget.username=admin
      - homepage.widget.password=${HTTP_PASSWORD}
      - homepage.widget.enableLeechProgress=true

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${USERDIR}/docker/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    networks:
      - arrflix
    labels:
      - homepage.group=Arr
      - homepage.name=prowlarr
      - homepage.icon=prowlarr.png
      - homepage.href=http://home-ubuntu:9696
      - homepage.description=Indexer
      - homepage.widget.type=prowlarr
      - homepage.widget.url=http://prowlarr:9696
      - homepage.widget.key=${PROWLARR_KEY}

  sonarr:
    image: mdhiggins/sonarr-sma
    container_name: sonarr
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${USERDIR}/docker/sonarr:/config
      - ${USERDIR}/docker/certs:/certs
      - ${DATADIR}/Downloads/completed:/data/completed
      - ${DATADIR}/Downloads/completed/recyclingBin:/data/completed/recyclingBin
      - ${DATADIR}/media/tvshows:/tvshows
    ports:
      - "8989:8989"
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - arrflix
    labels:
      - homepage.group=Media
      - homepage.name=Sonarr
      - homepage.icon=sonarr.png
      - homepage.href=http://home-ubuntu:8989
      - homepage.description=TV Series Management
      - homepage.widget.type=sonarr
      - homepage.widget.url=http://sonarr:8989
      - homepage.widget.key=${SONARR_KEY}
      - homepage.widget.enableQueue=true

  radarr:
    image: mdhiggins/radarr-sma
    container_name: radarr
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${USERDIR}/docker/radarr:/config
      - ${USERDIR}/docker/certs:/certs
      - ${DATADIR}/Downloads/completed:/data/completed
      - ${DATADIR}/Downloads/completed/recyclingBin:/data/completed/recyclingBin
      - ${DATADIR}/media/movies:/movies
    ports:
      - "7878:7878"
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - arrflix
    labels:
      - homepage.group=Media
      - homepage.name=Radarr
      - homepage.icon=radarr.png
      - homepage.href=http://home-ubuntu:7878
      - homepage.description=Movie Management
      - homepage.widget.type=radarr
      - homepage.widget.url=http://radarr:7878
      - homepage.widget.key=${RADARR_KEY}
      - homepage.widget.enableQueue=true

  bazarr:
    container_name: bazarr
    image: ghcr.io/hotio/bazarr:latest
    restart: unless-stopped
    # logging:
    #   driver: json-file
    # network_mode: bridge
    networks:
      - arrflix
    ports:
      - 6767:6767
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${USERDIR}/docker/bazarr:/config:rw
      - ${DATADIR}/media/tvshows:/tvshows
      - ${DATADIR}/media/movies:/movies
    labels:
      - homepage.group=Media
      - homepage.name=bazarr
      - homepage.icon=bazarr.png
      - homepage.href=http://home-ubuntu:6767
      - homepage.description=Subtitle Management
      - homepage.widget.type=bazarr
      - homepage.widget.url=http://bazarr:6767
      - homepage.widget.key=${BAZARR_KEY}

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${USERDIR}/docker/jellyfin:/config
      - ${DATADIR}/media/tvshows:/data/tvshows
      - ${DATADIR}/media/movies:/data/movies
    ports:
      - "8096:8096"
      - "8920:8920" # Optional
      - "7359:7359/udp" # Optional
      - "1900:1900/udp" # Optional
    restart: unless-stopped
    networks:
      - arrflix
      - proxy
    labels:
      - homepage.group=Movies
      - homepage.name=jellyfin
      - homepage.icon=jellyfin.png
      - homepage.href=http://home-ubuntu:8096
      - homepage.description=Media Server
      - homepage.widget.type=jellyfin
      - homepage.widget.url=http://jellyfin:8096
      - homepage.widget.key=${JELLYFIN_KEY}
      - homepage.widget.enableBlocks=true
      # - traefik.enable=true
      # - traefik.docker.network=proxy
      # - traefik.http.routers.jellyfin.entrypoints=http
      # - traefik.http.routers.jellyfin.rule=Host(`flix.adob.dev`) || Host(`dedsflix.adob.dev`)
      # - traefik.http.middlewares.jellyfin-https-redirect.redirectscheme.scheme=https
      # - traefik.http.routers.jellyfin.middlewares=jellyfin-https-redirect
      # - traefik.http.routers.jellyfin-secure.entrypoints=https
      # - traefik.http.routers.jellyfin-secure.rule=Host(`flix.adob.dev`) || Host(`dedsflix.adob.dev`)
      # - traefik.http.routers.jellyfin-secure.tls=true
      # - traefik.http.routers.jellyfin-secure.tls.certresolver=cloudflare
      # - traefik.http.routers.jellyfin-secure.service=jellyfin-dedsflix-arr-jrx17b
      # - traefik.http.services.jellyfin.loadbalancer.server.port=8096
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.jellyfin.entrypoints=http
      - traefik.http.routers.jellyfin.rule=Host(`dedsflix.adob.dev`)
      - traefik.http.middlewares.jellyfin-https-redirect.redirectscheme.scheme=https
      - traefik.http.routers.jellyfin.middlewares=jellyfin-https-redirect
      - traefik.http.routers.jellyfin-secure.entrypoints=https
      - traefik.http.routers.jellyfin-secure.rule=Host(`dedsflix.adob.dev`)
      - traefik.http.routers.jellyfin-secure.tls=true
      - traefik.http.routers.jellyfin-secure.tls.certresolver=cloudflare
      - traefik.http.routers.jellyfin-secure.service=jellyfin-dedsflix-arr-jrx17b

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - PORT=5055 #optional
    ports:
      - 5055:5055
    networks:
      - arrflix
      - proxy
    volumes:
      - ${USERDIR}/docker/jellyseerr:/app/config
      # - ${DATADIR}/media/tvshows:/data/tvshows
      # - ${DATADIR}/media/movies:/data/movies
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3
    restart: unless-stopped
    labels:
      - homepage.group=Movies
      - homepage.name=jellyseerr
      - homepage.icon=jellyseerr.png
      - homepage.href=http://home-ubuntu:5055
      - homepage.description=Media Server
      - homepage.widget.type=jellyseerr
      - homepage.widget.url=http://jellyseerr:5055
      - homepage.widget.key=${JELLYSEERR_KEY}
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.jellyseerr.entrypoints=http
      - traefik.http.routers.jellyseerr.rule=Host(`flixrequest.adob.dev`)
      - traefik.http.middlewares.jellyseerr-https-redirect.redirectscheme.scheme=https
      - traefik.http.routers.jellyseerr.middlewares=jellyseerr-https-redirect
      - traefik.http.routers.jellyseerr-secure.entrypoints=https
      - traefik.http.routers.jellyseerr-secure.rule=Host(`flixrequest.adob.dev`)
      - traefik.http.routers.jellyseerr-secure.tls=true
      - traefik.http.routers.jellyseerr-secure.tls.certresolver=cloudflare
      - traefik.http.routers.jellyseerr-secure.service=jellyseerr-dedsflix-arr-jrx17b
