version: "3.3"
networks:
  internal:
    driver: bridge

services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8080
    volumes:
      - ${USERDIR}/docker/qbittorrent:/config
      - ${DATADIR}/Downloads/completed:/data/completed
      - ${DATADIR}/Downloads/incomplete:/data/incomplete
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    networks:
      - internal
    labels:
      - homepage.group=Arr
      - homepage.name=qBittorrent
      - homepage.icon=qbittorrent.png
      - homepage.href=http://home-ubuntu:8080
      - homepage.description=Torrent client
      - homepage.widget.type=qbittorrent
      - homepage.widget.url=http://home-ubuntu:8080
      - homepage.widget.username=admin
      - homepage.widget.password=${HTTP_PASSWORD}

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${USERDIR}/docker/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    networks:
      - internal
    labels:
      - homepage.group=Arr
      - homepage.name=prowlarr
      - homepage.icon=prowlarr.png
      - homepage.href=http://home-ubuntu:9696
      - homepage.description=Indexer

  sonarr:
    image: mdhiggins/sonarr-sma
    container_name: sonarr
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${USERDIR}/docker/sonarr:/config
      - ${USERDIR}/docker/certs:/certs
      - ${DATADIR}/Downloads/completed:/data/completed
      - ${DATADIR}/Downloads/completed/recyclingBin:/data/completed/recyclingBin
      - ${DATADIR}/media/tvshows:/tvshows
    ports:
      - "8989:8989"
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - internal
    labels:
      - homepage.group=Arr
      - homepage.name=sonarr
      - homepage.icon=sonarr.png
      - homepage.href=http://home-ubuntu:8989
      - homepage.description=TV Series Management

  radarr:
    image: mdhiggins/radarr-sma
    container_name: radarr
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${USERDIR}/docker/radarr:/config
      - ${USERDIR}/docker/certs:/certs
      - ${DATADIR}/Downloads/completed:/data/completed
      - ${DATADIR}/Downloads/completed/recyclingBin:/data/completed/recyclingBin
      - ${DATADIR}/media/movies:/movies
    ports:
      - "7878:7878"
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - internal
    labels:
      - homepage.group=Arr
      - homepage.name=radarr
      - homepage.icon=radarr.png
      - homepage.href=http://home-ubuntu:7878
      - homepage.description=Movie Management

  bazarr:
    container_name: bazarr
    image: ghcr.io/hotio/bazarr:latest
    restart: unless-stopped
    # logging:
    #   driver: json-file
    # network_mode: bridge
    networks:
      - internal
    ports:
      - 6767:6767
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${USERDIR}/docker/bazarr:/config:rw
      - ${DATADIR}/media/tvshows:/data/tvshows:rw
      - ${DATADIR}/media/movies:/data/movies:rw
    labels:
      - homepage.group=Arr
      - homepage.name=bazarr
      - homepage.icon=bazarr.png
      - homepage.href=http://home-ubuntu:6767
      - homepage.description=Subtitle Management

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${USERDIR}/docker/jellyfin:/config
      - ${DATADIR}/media/tvshows:/data/tvshows
      - ${DATADIR}/media/movies:/data/movies
    ports:
      - "8096:8096"
      - "8920:8920" # Optional
      - "7359:7359/udp" # Optional
      - "1900:1900/udp" # Optional
    restart: unless-stopped
    networks:
      - internal
    labels:
      - homepage.group=Movies
      - homepage.name=jellyfin
      - homepage.icon=jellyfin.png
      - homepage.href=http://home-ubuntu:8096
      - homepage.description=Media Server
