---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- calendar:
    - agenda:
        widget:
          type: calendar
          firstDayInWeek: sunday
          view: monthly
          maxEvents: 10
          showTime: true
          integrations:
            - type: sonarr
              service_group: Media
              service_name: Sonarr
              color: teal
              params:
                unmonitored: true
            - type: ical
              url: https://pucminas.instructure.com/feeds/calendars/user_4NoLBIDVbglwAb5xBPXWtY8FByRFJCHZGHSW9Bec.ics
              name: PUC
              color: zinc
              params:
                showName: true
- Deployment:
    - DokPloy:
        icon: docker.png
        href: http://home-ubuntu:3000
# - Movies:
# - Arr:
