---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/info-widgets/

- resources:
    cpu: true
    memory: true
    uptime: true
    disk:
      - /
      - /mnt/arr/media

- search:
    provider:
      - duckduckgo
      - google
      - brave
    target: _blank

- datetime:
    text_size: xl
    format:
      dateStyle: short
      timeStyle: short
      hour12: true

- openmeteo:
    label: Belo Horizonte
    latitude: -19.9199
    longitude: -43.9423
    timezone: America/Sao_Paulo
    units: metric
    cache: 5
    format:
      maximumFractionDigits: 1
