# secrets:
#   cf-token:
#     file: ./cf-token.txt

networks:
  proxy:
    external: true
  monitoring:
    external: true

services:
  traefik:
    image: traefik:v3.3
    container_name: traefik
    restart: unless-stopped
    # command:
    # - "--api.dashboard=true"
    # - "--api.debug=true"
    # - "--api.insecure=true"
    # - "--entrypoints.http.address=:80"
    # - "--entrypoints.http.http.redirections.entrypoint.to=https"
    # - "--entrypoints.http.http.redirections.entrypoint.scheme=https"
    # - "--entrypoints.https.address=:444"
    # - "--entrypoints.metrics.address=:8082"
    # - "--entrypoints.tailscale.address=:443"
    # - "--serversTransport.insecureSkipVerify=true"
    # - "--providers.docker.endpoint=unix:///var/run/docker.sock"
    # - "--providers.docker.exposedbydefault=false"
    # - "--providers.file.filename=/config.yaml"
    # - "--certificatesresolvers.vpnresolver.tailscale=true"
    # - "--certificatesresolvers.cloudflare.acme.email=eu+cloudflare@andrebrandao.dev"
    # - "--certificatesresolvers.cloudflare.acme.storage=acme.json"
    # - "--certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare"
    # - "--certificatesresolvers.cloudflare.acme.dnschallenge.resolvers=1.1.1.1:53,1.0.0.1:53"
    # - "--log.level=INFO"
    # - "--log.filepath=/var/log/traefik/traefik.log"
    # - "--accesslog.filepath=/var/log/traefik/access.log"
    # - "--metrics.prometheus.entrypoint=metrics"
    # - "--metrics.prometheus.addserviceslabels=true"
    # - "--metrics.prometheus.addentrypointslabels=true"
    # - "--metrics.prometheus.buckets=0.1,0.3,1.2,5.0"

    security_opt:
      - no-new-privileges:true
    # secrets:
    #   - cf-token # the secret at the top of this file
    environment:
      # - TRAEFIK_DASHBOARD_CREDENTIALS=${TRAEFIK_DASHBOARD_CREDENTIALS}
      - CF_API_EMAIL=${CF_EMAIL}
      - CF_DNS_API_TOKEN=${CF_TOKEN}
    # network_mode: host
    networks:
      - proxy
      - monitoring
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      # ----
      - /home/deds/traefik/config/traefik.yaml:/traefik.yaml:ro
      - /home/deds/traefik/config/acme.json:/acme.json
      - /home/deds/traefik/config/config.yaml:/config.yaml:ro
      - /home/deds/traefik/logs:/var/log/traefik
      # ----
      - /var/run/tailscale/tailscaled.sock:/var/run/tailscale/tailscaled.sock
      - /var/lib/tailscale/certs/home-ubuntu.fable-company.ts.net.crt:/certs/home-ubuntu.fable-company.ts.net.crt
      - /var/lib/tailscale/certs/home-ubuntu.fable-company.ts.net.key:/certs/home-ubuntu.fable-company.ts.net.key
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
      - "443:443/udp"
      - "8080:8080" # Dashboard port
      - "8082:8082" # Metrics port
    labels:
      - homepage.group=Deployment
      - homepage.name=Traefik
      - homepage.description=Reverse proxy and load balancer
      - homepage.icon=traefik.png
      - homepage.href=http://home-ubuntu:8080
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.http.routers.traefik.rule=Host(`traefik.adob.dev`)"
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
      - "traefik.http.routers.traefik-secure.entrypoints=https"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik.adob.dev`)"
      # - "traefik.http.routers.traefik-secure.middlewares=traefik-auth"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.traefik-secure.tls.domains[0].main=adob.dev"
      - "traefik.http.routers.traefik-secure.tls.domains[0].sans=*.adob.dev"
      - "traefik.http.routers.traefik-secure.service=api@internal"

  cloudflared:
    container_name: cloudflare-tunnel
    image: "cloudflare/cloudflared:latest"
    restart: unless-stopped
    command: "tunnel --no-autoupdate --metrics 0.0.0.0:2000 run"
    environment:
      - "TUNNEL_TOKEN=${CF_TUNNEL_TOKEN}"
    ports:
      - "2000:2000"
    networks:
      - proxy
      - monitoring
    labels:
      - homepage.group=Deployment
      - homepage.name=Cloudflare Tunnel
      - homepage.description=Cloudflare Tunnel for secure access
      - homepage.icon=cloudflare.png

    # network_mode: host
    # labels:
    # - homepage.group=Deployment
    # - homepage.title=Cloudflare Tunnel
    # - homepage.icon=cloudflare.png
    # - homepage.widget.type=cloudflared
    # - homepage.widget.accountid=${CLOUDFLARE_ACCOUNT_ID}
    # - homepage.widget.tunnelid=${CLOUDFLARE_TUNNEL_ID}
    # - homepage.widget.key=${CLOUDFLARE_TUNNEL_KEY}

  # cloudflare-companion:
  #   image: tiredofit/traefik-cloudflare-companion
  #   container_name: cloudflare-companion
  #   volumes:
  #     - /home/deds/cloudflare-companion/logs:/logs
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   environment:
  #     - TIMEZONE=America/Sao_Paulo

  #     - LOG_TYPE=BOTH
  #     - LOG_LEVEL=INFO

  #     - TRAEFIK_VERSION=2
  #     - CF_EMAIL=${CF_EMAIL}
  #     - CF_TOKEN=${CF_TOKEN}
  #     - RC_TYPE=CNAME

  #     - TARGET_DOMAIN=${CF_TARGET_DOMAIN}
  #     - DOMAIN1=${DOMAIN1}
  #     - DOMAIN1_ZONE_ID=${DOMAIN1_ZONE_ID}
  #     #- DOCKER_HOST=tcp://198.51.100.32:2376
  #     #- DOCKER_CERT_PATH=/docker-certs
  #     #- DOCKER_TLS_VERIFY=1

  #     #- TRAEFIK_FILTER_LABEL=traefik.constraint
  #     #- TRAEFIK_FILTER=proxy-public
  #   networks:
  #     - dokploy-network
  #   restart: always
